name: benchdata publish
on: push

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: gobenchdata publish
        uses: bobheadxi/gobenchdata@v1
        with:
          PUBLISH: true
          PUBLISH_BRANCH: gh-pages
          PRUNE_COUNT: 30
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
